CREATE TABLE MESSAGE
(
    NUMMESSAGE NUMBER(10)  NOT NULL,
    NUMSUJET NUMBER(5)  NOT NULL,
    NUMMEMBRE NUMBER(5)  NOT NULL,
    TEXMESSAGE CLOB  NOT NULL,
    DTEMESSAGE DATE  NOT NULL,
    NSUMESSAGE NUMBER(4)  NOT NULL
);